"""add bio to user

Revision ID: 01706a350589
Revises: 20260525_0003
Create Date: 2026-05-25 17:13:45.154905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '01706a350589'
down_revision: Union[str, Sequence[str], None] = '20260525_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'visibility',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('public', 'authenticated', 'private', 'staff_only', name='post_visibility', native_enum=False),
               existing_nullable=False)
    op.alter_column('posts', 'moderation_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('visible', 'hidden', name='post_moderation_status', native_enum=False),
               existing_nullable=False)
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.alter_column('posts', 'moderation_status',
               existing_type=sa.Enum('visible', 'hidden', name='post_moderation_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('posts', 'visibility',
               existing_type=sa.Enum('public', 'authenticated', 'private', 'staff_only', name='post_visibility', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
