"""delete bio from user

Revision ID: 6e8a0b958885
Revises: 01706a350589
Create Date: 2026-05-25 17:47:48.879122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6e8a0b958885'
down_revision: Union[str, Sequence[str], None] = '01706a350589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
